src/App.jsx
src/pages/FollowPage/index.jsx
src/pages/HomePage/index.jsx
src/pages/LoginPage/index.jsx
src/pages/MyInfoEditPage/index.jsx
src/pages/MyInfoPage/index.jsx
src/pages/MyPage/index.jsx
src/pages/NotFoundPage/index.jsx
src/pages/NotificationPage/index.jsx
src/pages/PostAddPage/index.jsx
src/pages/PostDetailPage/index.jsx
src/pages/PostEditPage/index.jsx
src/pages/SearchPage/index.jsx
src/pages/SearchTagPage/index.jsx
src/pages/SignupPage/index.jsx
src/pages/UserPage/index.jsx
src/pages/index.jsx
src/routes/Router.jsx

#4
router를 추가하고 페이지 컴포넌트를 만들었습니다.  
- router 추가
- 페이지 컴포넌트 추가

Feat: router 추가

---

src/components/basic/Button/index.jsx
src/stories/components/basic/Button.stories.jsx
src/utils/constants/colors.js

#2 
공통된 Button 컴포넌트 - 전역에서 사용
- props
- hover,active 속성은 기본값이 주로 사용될 거라 예상됩니다. 
해당 속성 기본값으로 hover, active 된 요소가 색이 변합니다. (filter사용)
- width는 기본값 100% 이지만 조절 가능합니다. 
- height는 피그마 70px을 기본으로 줬습니다.

feat: Button 컴포넌트 생성

---

src/components/basic/Avatar/index.js
src/stories/basic/Avatar.stories.jsx

#18 
Avatar 컴포넌트
- Avatar 컴포넌트 추가하고 storybook에 연결했습니다.
- 불필요한 props는 삭제했습니다.
- border와 bg 컬러는 전역 스타일명이 적용되지 않아서 추후 변경 예정입니다.

feat: Avatar 컴포넌트 구현

---

src/App.jsx
src/index.jsx
src/routes/Router.jsx

defaultTemplate가 BrouswerRouter 바깥에 있어서 defaultTemplate 내부에서는
react-router-dom의 기능을 사용할 수 없는 문제 발생
BrowserRouter를 index.jsx로 이동시켜 App 컴포넌트 전체를 감싸도록 수정

refactor: BrowserRouter를 index.jsx로 이동

---

.gitignore
src/App.jsx
src/contexts/UserContext/handles.jsx
src/contexts/UserContext/index.jsx
src/contexts/UserContext/reducer.jsx
src/contexts/UserContext/types.jsx
src/contexts/index.jsx
src/hooks/useLocalStrorage.js
src/hooks/useLocalToken.jsx
src/routes/Router.jsx
src/styles/index.css
src/template/DefaultTemplate.jsx
src/utils/apis/common.js
src/utils/apis/userApi.js
src/utils/constants/apiMethods.js

#5 
* contexts 폴더 추가
* UserContext 및 UserProvider 추가
* useLocalToken 추가
* Axios 기본 설정 추가
* userApi 추가
User 관련 데이터 및 메서드를 전역 공급하는 역할을 수행합니다. 
사용자 token을 로컬 스토리지로 관리하는 커스텀 훅입니다. 
Axios의 instance를 생성하고 `REACT_APP_API_URL`을 등록하였습니다. 
응답 처리 로직을 추가하였습니다. 
User 관련 Api를 추가하였습니다. 
Axios를 사용했습니다.

Feat: Userprovider 및 userApi 추가

---

src/components/basic/Badge/index.jsx
src/stories/basic/Badge.stories.jsx

알림 아이콘에 붙일 Badge 컴포넌트
해당 앱에선 Dot형태로만 사용되기 때문에 count를 확인하는 props는 삭제했습니다.

feat: Badge 컴포넌트 구현

---

src/components/basic/Button/index.jsx
src/stories/components/basic/Button.stories.jsx

기존 오류 수정 및 disabled 옵션 추가
1. 아래처럼 스타일 오류 있던 부분 수정
2. disabled 옵션추가
(disabled 상태의 경우 active, hover style 적용 제한)

refactor: Button 컴포넌트 style 오류 수정 및 disabled 옵션 추가

---

src/components/LoginModal/index.jsx

#51
1. 잘못된 이메일/비밀번호로 로그인 요청시 실패 모달 띄움.
2. 배경 부분이나 확인 버튼을 누르면 닫힘

feat: LoginModal 컴포넌트 구현

---

src/components/LoginForm/index.jsx

fix(LoginForm): LoginForm 컴포넌트 스타일 수정

---

src/components/LoginForm/index.jsx
src/components/LoginModal/index.jsx
src/pages/LoginPage/index.jsx

#34 
로그인 페이지 구현
1. 로그인 성공시 포스트 피드 페이지로 이동
2. 이메일 / 비밀번호 미입력시 에러메시지
3. 아이디 or 비밀번호 일치하지 않을 경우 모달창 띄우기
4. 회원가입 페이지 이동 텍스트

feat: LoginPage 구현

---

src/components/LoginForm/index.jsx
src/components/LoginModal/index.jsx
src/components/SignupModal/index.jsx
src/pages/SignupPage/index.jsx

#35 
1. 기본 화면
2. 회원가입 후 바로 로그인 요청 
3. 바로 MainPage로 이동.

feat: SignupPage 페이지 구현

---

src/components/LoginModal/index.jsx
src/components/SignupModal/index.jsx
src/contexts/UserContext/handles.jsx
src/contexts/UserContext/index.jsx
src/pages/LoginPage/index.jsx
src/pages/MainPage/index.jsx
src/pages/SignupPage/index.jsx

feat: 로그인, 회원가입 페이지 userProvider작성

---

src/components/TagAddForm/index.jsx
src/components/TagSearchResult/index.jsx
src/components/UploadImage/index.jsx
src/components/UserSearchResult/index.jsx
src/index.jsx
src/utils/constants/images.js

컴포넌트를 분리하면서 에러가 생겨서 다시 수정했습니다.

fix: SearchPage 탭 이동 시 계정 검색 오류 수정

---

src/components/Profile/index.jsx
src/components/basic/Text/index.jsx
src/utils/constants/images.js

Profile 컴포넌트를 추가했습니다. 
디자인 시안에 맞게 기본값을 넣었기 때문에 아래와 같이 간단히도 사용 가능합니다. 
아래와 같은 시안은 유사해 보이지만 적용이 어렵습니다. (억지로 적용할 순 있지만 조금 어색하군요)
일단 Profile이 아니기도 해서 제외했습니다. 
기본적으로 Avatar와 Text 컴포넌트 등으로 구성됩니다. 자세한 것은 코드를 참고해 주세요.
Text 컴포넌트에서 fontWeight 부분을 수정했습니다. 
현재는 strong 속성에 따라 bold 또는 undefined 인데요,
이 방식으로는 fontWeight의 값을 디테일하게 조정하기 어렵습니다.
아래와 같이 fontWeight 값을 받을 수 있도록 했습니다.

feat: Profile 컴포넌트 추가

---

src/pages/MainPage/PostBody.jsx
src/pages/MainPage/PostHeader.jsx
src/pages/PostDetailPage/index.jsx

MainPage와 PostDetailPage에 Profile 컴포넌트를 적용했습니다.

refactor: 메인페이지와 게시물상세 페이지에 Profile 컴포넌트 적용

---

src/components/basic/Icon/IconButton.jsx
src/components/basic/Icon/IconLink.jsx
src/components/basic/Icon/index.jsx
src/styles/index.css

#92 
- 아이콘을 감싸는 button과 Link 컴포넌트를 추가했습니다.
- 기본적으로 아래와 같이 사용 가능합니다.
- 내부에 자식을 넣는다면 아이콘은 앞으로 위치하게 됩니다.
- 추가/수정해야 될 부분이 있다면 코멘트 부탁드립니다.

feature: IconButton, IconLink 컴포넌트 추가

---

src/components/FixedContainer/index.jsx
src/components/Header/Header.jsx
src/components/Navigation/index.jsx
src/components/basic/Icon/IconButton.jsx
src/components/basic/Icon/IconLink.jsx
src/components/basic/Icon/index.jsx
src/components/basic/pageWrapper/index.js
src/pages/PostAddPage/index.jsx
src/styles/index.css

- Header, Navigation과 PostAddPage의 게시물 등록 버튼 부분이 화면에 고정되어 있는데
이 부분을 위해 만든 컴포넌트입니다.
- 내부속성에 top/bottom으로 위치 지정이 가능하며 아래와 같이 사용 가능합니다.
- props는 아래와 같은 값을 받습니다.
- 추가로 Header, Navgation, PostAddPag 버튼에 적용 완료하였습니다.

feat: FixedContainer 컴포넌트 추가

---

src/contexts/UserContext/handles.jsx
src/pages/SignupPage/index.jsx

#64 
handleSignup에서 회원가입 완료시 login시도하는 코드 추가했습니다.
1. 회원가입 요청
2. 회원가입 성공, 페이지 이동
3. postman 사용하여 확인
로그인된 유저 요청(users/online-users)하면 로그인 된 것 확인 가능합니다

feat: 회원가입 로직 수정

---

src/pages/MainPage/PostBody.jsx
src/pages/MainPage/PostHeader.jsx
src/pages/MainPage/PostItem.jsx
src/pages/MainPage/index.jsx
src/pages/PostDetailPage/PostDetail.jsx
src/pages/PostDetailPage/index.jsx

#87 
포스트에 글 '더보기' 버튼을 추가했습니다. 
더보기 버튼 클릭 시, 말줄임을 해제하고 전체 텍스트를 보여줍니다.
아래는 시연 영상입니다. 
https://user-images.githubusercontent.com/80658269/174139064-f6b2c8c6-aa0e-4f29-a0d2-39ab9fb8e7f3.mp4
기능은 구현했으나, 코드가 다소 복잡하게 작성되었습니다. 
추후에 리팩터링을 하겠습니다.  
시간이 되신다면 리뷰를 부탁드려요 :)
그 외 PostDetailPage에 대한 작은 버그들을 수정하고 개선했습니다. 
예) 본인 포스트가 아님에도 설정 버튼이 보이는 버그 수정

feat: 포스트에 더보기 버튼 추가

---

src/pages/PostAddPage/index.jsx
src/utils/apis/postApi.js

- 테스트를 위해 토큰을 지정해서 사용하다가
실제 유저의 토큰으로 받아서 사용하는 것으로 변경하였습니다.
- 일부 코드를 분리시켰습니다.
- 공통으로 사용하는 코드는 다른 파일로 이동시킬 예정입니다.

refactor: PostAddPage 실제 유저 토큰 연결

---

public/index.html

chore: meta 태그에 http-equiv 설정 추가

---

netlify.toml
src/utils/apis/postApi.js
src/utils/apis/userApi.js

feat: netlify toml proxy 설정 추가

---

src/utils/apis/postApi.js

chore: 오타 수정

---

netlify.toml
package.json
public/index.html
src/pages/MainPage/PostBody.jsx
src/pages/MyPage/index.jsx
src/pages/UserPage/index.jsx
src/utils/apis/postApi.js
src/utils/apis/userApi.js

- 현재 CORS를 서버에서 열어놔서 프록시가 필요없음. 근데 https -> http 요청중 아래로 해결
프록시 전부 제거 및 http-equiv meta 태그 추가 
-> 배포 후 네트워크 에러 해결될지?

chore: 프록시 전부 제거 및 http-equiv meta 태그 추가

---

src/components/Header/Header.jsx

fix: notification page link 수정

---

src/pages/LoginPage/index.jsx
src/pages/SignupPage/index.jsx

로그인 / 회원가입 페이지 PageWrapper 추가하고 너비 줄였을때 한쪽으로 몰리는 문제 해결했습니다.

style: pageWrapper 추가 및 width 작업

---

src/components/Card/index.jsx
src/components/NotificationCard/index.jsx
src/pages/NotificationPage/index.jsx

알림 페이지 구현입니다.
팔로우와 알림 보내는건 포스트맨 사용하였습니다.

feat: Notification Page 구현

---

src/components/Message/NoResultMessage.jsx
src/components/TagSearchResult/index.jsx
src/components/UserSearchResult/index.jsx
src/components/basic/Text/index.jsx
src/pages/SearchPage/index.jsx
src/pages/SearchTagPage/index.jsx
src/routes/Router.jsx

- 태그 검색 시 params을 토대로 변경되게 수정했습니다.
- 태그 검색의 url은 tag/:tag로 변경했습니다.
- 검색 후 빈 배열로 내려올 경우 검색 결과 없음 메세지를 출력하도록 변경했습니다.
- 계정 클릭 시 해당 계정으로 이동되게 변경했습니다.
+ 추가로 Text에 propsStyle적용 안된다고 하셔서 props 위치 옮겼습니다.

refactor: 검색 페이지(searchPage/SearchTagPage) 수정

---

src/pages/MainPage/PostBody.jsx
src/pages/MainPage/PostHeader.jsx
src/pages/MainPage/PostItem.jsx
src/pages/PostDetailPage/index.jsx
src/routes/Router.jsx
src/utils/apis/userApi.js
src/utils/functions/displayedAt.js

삭제 후 메인페이지로 이동합니다. 
수정 버튼 클릭 시 게시물 작성 페이지로 이동합니다. 
보내는 함수는 아래와 같습니다. 
좋아요 및 댓글 작성 시 알림을 보내도록 처리했습니다. 
나중에 필요하다면 알림 처리 API도 추가할 예정입니다. 
'방금 전', '3분 전', '2시간 전', '5일 전' 등 경과 시간을 계산하는 함수를 추가했습니다. 
utils 폴더에 있습니다. 
아래와 같이 적용했습니다. 
최근에 작성한  댓글이 위에 오도록 수정했습니다.

feat: 포스트 삭제 및 알람 기능 추가 등

---

src/components/FollowList/MyFollowList.jsx
src/contexts/UserContext/handles.jsx
src/contexts/UserContext/index.jsx
src/contexts/UserContext/reducer.jsx

refactor: follow페이지 수정

---

src/components/TagSearchResult/index.jsx
src/components/UserSearchResult/index.jsx
src/pages/SearchPage/index.jsx

- 빈 검색어 입력 시 에러메세지 나타나는 부분 수정 => 에러 메세지가 나타나지 않는 대신 입력 제한을 추가했습니다.
- 검색되지 않은 상태에서는 검색결과 없음 메세지는 출력되지 않도록 수정했습니다.

refactor: 검색페이지(searchPage) 메세지 수정

---

src/components/Card/index.jsx
src/components/LoginForm/index.jsx
src/components/NotificationCard/index.jsx
src/components/SignupForm/index.jsx
src/pages/LoginPage/index.jsx
src/pages/NotificationPage/index.jsx

1. 로그인 / 회원가입 / 알림 페이지 스타일 수정
위와 같이 짤리는 문제
이렇게 해결하였습니다.
(로그인 / 회원가입 페이지도 동일하게 수정하였습니다)
2. 알림 페이지 레이아웃 문제
위와 같이 하단 레이아웃 깨지는 문제
height 조절해서 해결 하였습니다.

refactor: page-style

---

src/utils/functions/userLevel/getUserLevel.js

유저 레벨을 반환하는 함수가 점수(score)도 반환하도록 수정했습니다. 
객체로 반환합니다. 구조 분해 할당을 사용하세요 :)

refactor: getUserLevel 함수가 score도 반환하도록 수정

---

src/components/Modal/ModalContent.jsx
src/components/TagAddForm/index.jsx
src/components/UploadImage/index.jsx

- modal에서 title or description 안적을 경우 Text 에러 발생하던 부분 수정했습니다.
- isEmphasis 에러발생하던 부분 수정했습니다.
- 추가로 png 이미지 업로드 시 자동으로 배경색상이 들어가도록 변경하였습니다.

fix: 게시물 등록/수정 페이지 에러 수정

---

src/utils/apis/postApi.js

나에게 온 알림을 읽음 처리하는 API를 추가했습니다. 
참고로 GET이 아니라 PUT이 맞습니다.

feat: 알림 확인 처리 API 추가

---

src/pages/LoginPage/index.jsx

새로 업로드 된 로고로 변경 하였습니다 ~
화면 줄였을때 같이 줄어드는 부분 확인 하였습니다.

refactor: 변경 Logo로 수정

---

src/components/UserSearchResult/index.jsx

feature: 유저 검색 결과(UserSearchResult)에 프로필 이미지 연결

---

src/components/SignupForm/index.jsx

fix: 에러 메시지 수정

---

src/pages/MainPage/PostBody.jsx
src/pages/PostDetailPage/index.jsx

디자인 시안에 맞게 MainPage 및 PostDetailPage의 스타일을 수정했습니다.

style: 디자인 시안에 맞게 스타일 수정

---

src/components/PostImageContainer/index.jsx
src/contexts/UserContext/handles.jsx
src/contexts/UserContext/index.jsx
src/pages/MyInfoEditPage/index.jsx
src/pages/UserPage/UserData.jsx
src/pages/UserPage/index.jsx
src/pages/UserPage/style.jsx
src/utils/apis/userApi.js

> context, handler, api 에서 userName prop 삭제

fix: UserPage & MyInfo 수정 반영

---

src/components/SignupForm/index.jsx

refactor: validation text 여백 조정

---

src/components/SignupForm/index.jsx
src/components/basic/Input/index.jsx
src/hooks/useValidInputs.js

1. 비밀번호 체크 input 길이 제한 추가
2. onBlur속성 사용해서 tab키 누르거나 다른 곳 이동 시에도 validation 하게 하였습니다.

fix: SignupForm 수정사항 반영

---

src/pages/LoginPage/index.jsx
src/pages/SignupPage/index.jsx

refactor: 모달 메시지 수정

---

src/pages/PostEditPage/index.jsx
src/pages/SearchPage/UserSearchResult.jsx

게시물 페이지에서 게시글 등록 버튼을 연속으로 누를 시
중복으로 서버에 요청되던 부분을 수정했습니다.

Fix: 게시물 등록 페이지 버튼 클릭시 중복 서버요청 수정

---

src/pages/MyInfoPage/UserLevel.jsx

- 페이지 내에서 서버 요청에 요청하여 User의 데이터를 받아오던 부분을
context의 currentUser의 데이터를 가져오도록 내부 로직을 수정했습니다.

refactor: Level 관련 데이터 currentUser에서 받아오도록 수정

---

src/pages/MyInfoPage/LevelModal.jsx
src/pages/MyInfoPage/UserLevel.jsx
src/utils/functions/userLevel/getUserLevel.js

fix/UserLevel 활동 시 얻는 활동 점수 재조정

---

src/components/Header/index.jsx

1. 데이터 fetching부분 useCallback 사용
2. 알림 없는 경우 에러 해결
사용자가 가진 알림이 아예 없는 경우 요런 에러가 발생하더라구요.
제가 테스트용으로 사용하던 계정들은 기존에 알림이 다 존재했어서 생각 못 한 부분이었습니다.
방어코드 추가해서 해결했습니다

fix: 알림 오류 해결 및 useCallback사용

---

src/components/FollowList/MyFollowList.jsx
src/components/PostImageContainer/index.jsx
src/pages/FollowPage/index.jsx
src/pages/MyInfoEditPage/index.jsx
src/pages/MyInfoPage/UserDetails.jsx
src/pages/UserPage/PostData.jsx
src/pages/UserPage/UserData.jsx
src/pages/UserPage/index.jsx

refactor: 내정보 페이지 개선

---

src/pages/MainPage/PostBody.jsx
src/pages/MainPage/PostHeader.jsx
src/pages/MainPage/index.jsx
src/pages/NotFoundPage/index.jsx
src/pages/PostDetailPage/index.jsx

refactor: 불필요한 useCallback 삭제
